apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: meal-planner-app
  name: meal-planner-app
  namespace: mealplanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meal-planner-app
  strategy: {}
  template:
    metadata:
      labels:
        app: meal-planner-app
    spec:
      containers:
      - image: soberblue/mealplanner:1.2.1
        name: mealplanner
        ports:
        - containerPort: 3000
        resources: {}
        envFrom:
        - configMapRef: 
            name: mealplanner-database-config
status: {}


# docker buildx build \
#  --platform linux/amd64 \
#  -t soberblue/mealplanner:1.2.1 \
#  --push .