apiVersion: v1
kind: Service
metadata:
  labels:
    app: mealplanner-redis-hsvc
  name: mealplanner-redis-hsvc
  namespace: mealplanner
spec:
  clusterIP: None
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    app: mealplanner-redis
  type: ClusterIP
status:
  loadBalancer: {}