apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealplanner-pvc
  namespace: mealplanner
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: mealplanner-pv
  
