apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: meal-planner-app
  name: meal-planner-app
  namespace: mealplanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meal-planner-app
  strategy: {}
  template:
    metadata:
      labels:
        app: meal-planner-app
    spec:
      volumes:
      - name: log-dir
        emptyDir: {}
      - name: alloy-config
        configMap:
          name: mealplanner-alloy-sidecar
      containers:
      - image: soberblue/mealplanner:1.6.0
        name: mealplanner
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: log-dir
          mountPath: /var/log/mealplanner
        resources: 
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 500Mi
        envFrom:
        - configMapRef: 
            name: mealplanner-database-config
        - configMapRef: 
            name: mealplanner-configmap
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mealplanner-redis-secret
              key: REDIS_PASSWORD
        # checks when the pod has finished starting
        startupProbe:
          httpGet:
            path: /health
            port: 3000
          failureThreshold: 30
          periodSeconds: 10
        #  checks when pod is failing and will restart
        livenessProbe:
          timeoutSeconds: 3
          failureThreshold: 3
          periodSeconds: 15
          terminationGracePeriodSeconds: 10
          httpGet:
            path: /api/health
            port: 3000
        # checks when pod is broken and will mark as unready 
        readinessProbe:
          failureThreshold: 5 #how many times the pod can fail before marking as unready
          periodSeconds: 30 #how often to probe the pod
          httpGet:
            path: /api/ready
            port: 3000
      # export logs to grafana
      - image: grafana/alloy:latest
        name: alloy
        args:
          - "run"
          - "/etc/alloy/alloy-sidecar.yaml"
        volumeMounts:
        - name: alloy-config
          mountPath: /etc/alloy/
        - name: log-dir
          mountPath: /var/log/mealplanner
    
status: {}


# docker buildx build --platform linux/amd64 -t soberblue/mealplanner:1.6.0 --push .