apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: meal-planner-app
  name: meal-planner-app
  namespace: mealplanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meal-planner-app
  strategy: {}
  template:
    metadata:
      labels:
        app: meal-planner-app
    spec:
      containers:
      - image: soberblue/mealplanner:1.4.1
        name: mealplanner
        ports:
        - containerPort: 3000
        resources: 
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 500Mi
        envFrom:
        - configMapRef: 
            name: mealplanner-database-config
        - configMapRef: 
            name: mealplanner-configmap
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mealplanner-redis-secret
              key: REDIS_PASSWORD
status: {}


# docker buildx build --platform linux/amd64 -t soberblue/mealplanner:1.3.0 --push .