apiVersion: v1
kind: PersistentVolume
metadata:
  name: mealplanner-pv
spec:
  accessModes:
      - ReadWriteOnce
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: bigkev-storage   # reuse existing SC
  nfs:
    server: 192.168.1.65
    path: /mnt/pve/bigkev/mealplanner-db
  claimRef:
    name: mealplanner-pvc
    namespace: mealplanner