apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealplanner-redis-pvc
  namespace: mealplanner
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: mealplanner-redis-pv
  resources:
    requests:
      storage: 2Gi
  storageClassName: bigkev-storages